# -*- coding: utf-8 -*-
"""gradio_layouts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BrUyt6b36dCXtbBLpm173gMelfQG7Fk
"""

import gradio as gr

"""Blocks > Tabs > Rows > Columns"""

with gr.Blocks() as demo:
    with gr.Tab("Tab One"):
        with gr.Row():
            text1 = gr.Text(value="Output One")
            text2 = gr.Text(value="Output Two")
    with gr.Tab("Tab Two"):
      with gr.Row():
        text1 = gr.Text(value="Output One")
        text2 = gr.Text(value="Output Two")
      with gr.Row():
        with gr.Column():
          text1 = gr.Text(value="Output One")
          text2 = gr.Text(value="Output Two")
        with gr.Column():
          text1 = gr.Text(value="Output three")


demo.launch()

"""Accordion"""

with gr.Blocks() as demo:
    gr.Label("Label here")
    with gr.Accordion("Accordion One", open=False):
        with gr.Row():
            text1 = gr.Text(value="Output One")
            text2 = gr.Text(value="Output Two")
demo.launch()

"""Images"""

with gr.Blocks() as demo:
    gr.Button("Button One")
    gr.Button("Button Two")
    image = gr.Image()
demo.launch()

"""Component Interaction"""

def multiply(x,y):
    return x*y

with gr.Blocks() as app:
    with gr.Row():
        x_slider = gr.Slider()
        y_slider = gr.Slider()

    with gr.Row():
        result= gr.Text()

    x_slider.change(fn=multiply, inputs=[x_slider, y_slider], outputs=[result])

    y_slider.change(fn=multiply, inputs=[x_slider, y_slider], outputs=[result])
app.launch()
#

from PIL import Image

def makegrayscale(image_path):
    image = Image.open("sample_data/img.jpg")
    return image.convert("L"), "Converted"
#

image, log = makegrayscale("sample_data/img.jpg")
#

with gr.Blocks() as demo:
  with gr.Row():
    image_input = gr.Image(type="filepath")
    output_image = gr.Image()
  with gr.Row():
     log = gr.Text()
     submit= gr.Button("Submit")
     submit.click(fn=makegrayscale, inputs=[image_input], outputs=[output_image, log])
demo.launch()

"""GUI Example"""

from transformers import AutoImageProcessor, AutoModelForImageClassification

processor = AutoImageProcessor.from_pretrained("microsoft/resnet-18")
model = AutoModelForImageClassification.from_pretrained("microsoft/resnet-18")

def classify_image(image):
  image = processor(image, return_tensors="pt")["pixel_values"]
  logits = model(image).logits

  predicted_label = logits.argmax(-1).item()
  return model.config.id2label[predicted_label]
#

gIface = gr.Interface(fn=classify_image,
                      inputs=gr.Image(),
                      outputs=gr.Label(),
                      title="RESR",
                      description="Upload")
gIface.launch()

"""Pipelines Integration"""

from transformers import pipeline
sentiment_analysis = pipeline("sentiment-analysis")

sentiment_analysis("I am sad")

def predict_sentiment(text):
  result = sentiment_analysis(text)
  return result[0]["label"], result[0]["score"]

predict_sentiment("I am Happy")
#

iface = gr.Interface(fn=predict_sentiment,
                     inputs=gr.Textbox(lines=2,placeholder="Enter your review here..."),
                     outputs=[gr.Text(label="Sentiment"), gr.Number(label="Confidence Score")]  )
iface.launch()

demo = gr.load("distilbert/distilbert-base-uncased-finetuned-sst-2-english", src="models")
demo.launch()
#