# -*- coding: utf-8 -*-
"""hf_audio-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vpLqRT5Pe1YSk6cVs7tVImmkiv-y8uW
"""

import torch
import torchaudio
import transformers
import diffusers

from transformers import AutoFeatureExtractor, AutoModelForAudioClassification

feature_extractor = AutoFeatureExtractor.from_pretrained("facebook/wav2vec2-base-960h")

import librosa

audio_path = "sample_data/audio.mp3"

y, sr = librosa.load(audio_path, sr=16000)

sr

extractor = AutoFeatureExtractor.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")
model = AutoModelForAudioClassification.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")

result = extractor(y, sampling_rate=sr, return_tensors="pt")

result

with torch.no_grad():
    prediction_logits = model(**result).logits

predicted_class_ids = torch.argmax(prediction_logits, dim=-1).item()
print(f"Predicted class: {model.config.id2label[predicted_class_ids]}")

predicted_class_ids = torch.argmax(prediction_logits, dim=-1).item()
print(f"Predicted class: {model.config.id2label[predicted_class_ids]}")

predicted_class_ids



model.config.id2label

from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="facebook/wav2vec2-base-960h")

pipe(audio_path)