# -*- coding: utf-8 -*-
"""hf-audio-transcribe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvvYAnZ2HjPwsUv366r0IdDxd8jJqFer

Combine models and tools
"""

pip install pyannote.audio

from pyannote.audio import Pipeline
from google.colab import userdata

# Ensure you have a secret named 'HF_TOKEN' in the Colab secrets tab
try:
    token = userdata.get('HF_TOKEN')
    diarization_pipeline = Pipeline.from_pretrained(
        "pyannote/speaker-diarization-3.1",
        token=token
    )
    print("Pipeline loaded successfully!")
except Exception as e:
    print(f"Error: {e}")
    print("Make sure you have accepted the terms at https://hf.co/pyannote/speaker-diarization-3.1 and added your HF_TOKEN to Colab secrets.")

from pyannote.audio.pipelines.utils.hook import ProgressHook

with ProgressHook() as hook:
  diarization = diarization_pipeline("sample_data/audio1.mp3", hook)

diarization

diarization.serialize

diarization.exclusive_speaker_diarization