# -*- coding: utf-8 -*-
"""hf-audio-generate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5dM2Lrnm-PQd3haJABm-l-XXURMRnF_
"""

import transformers

from transformers import pipeline
pipe=  pipeline("text-to-speech")

text = "Hello, How are you today?"
output = pipe(text)

output['audio']

output['sampling_rate']

output

from IPython.display import Audio
Audio(output['audio'], rate=output['sampling_rate'])

from pydub import AudioSegment

audio_seg = AudioSegment(
    output['audio'].tobytes(),
    frame_rate=output['sampling_rate'],
    sample_width=4,
    channels=1
)

audio_seg.export("example.mp3", format="mp3")