# -*- coding: utf-8 -*-
"""hf-course-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ps8FsGw8fldQKS2HwBWUtzh6OCDFifi_

# **LLM Basics**

**NLP**: The broader field focused on enabling computers to understand, interpret, and generate human language.

**LLMs**: A powerful subset of NLP models characterized by their massive size, extensive training data, and ability to perform a wide range of language tasks with minimal task-specific training.

## Hugging Face Ecosystem
- **Transformers** - NLP Tasks
- **Diffusers** - Image / Video
- **Datasets** - For ML
- **Tokenizers** - For text data
- **Accelerate** - Train PyTorch models
- **Hugging Face Hub** - Platform for ML

## Transformer library
- Solve problems in NLP, computer vision, audio processing, and more
- The most basic object in the Transformers library is the pipeline() function (connects a model with its necessary preprocessing and postprocessing steps).
- The pipeline() function supports multiple modalities, allowing us to work with text, images, audio, and even multimodal tasks
"""

# Example of using transformer
from transformers import pipeline

pipeline = pipeline("sentiment-analysis")
pipeline("I've been waiting for a HuggingFace course my whole life.")

# Passing several sentences
pipeline(
    ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]
)

"""This pipeline selects a particular pretrained model that has been fine-tuned for sentiment analysis in English. The model is downloaded and cached when you create the pipeline object. If you rerun the command, the cached model will be used instead and there is no need to download the model again.

### **Available Pipelines**

- **Text pipelines**
    - text-generation: Generate text from a prompt
    - text-classification: Classify text into predefined categories
    - summarization: Create a shorter version of a text while preserving key information
    - translation: Translate text from one language to another
    - zero-shot-classification: Classify text without prior training on specific labels
    - feature-extraction: Extract vector representations of text

- **Image pipelines**
    - image-to-text: Generate text descriptions of images
    - image-classification: Identify objects in an image
    - object-detection: Locate and identify objects in images

- **Audio pipelines**
    - automatic-speech-recognition: Convert speech to text
    - audio-classification: Classify audio into categories
    - text-to-speech: Convert text to spoken audio

- **Multimodal pipelines**
    - image-text-to-text: Respond to an image based on a text prompt
"""

# text generation example
from transformers import pipeline

generator = pipeline("text-generation")
generator("In this course, we will teach you how to")

# Use model from Hub
from transformers import pipeline

generator = pipeline("text-generation", model="HuggingFaceTB/SmolLM2-360M")
generator(
    "In this course, we will teach you how to",
    max_length=30,
    num_return_sequences=2,
)

"""Audio"""

from transformers import pipeline
import requests
import librosa

# 1. Initialize the pipeline
transcriber = pipeline(
    task="automatic-speech-recognition",
    model="openai/whisper-base.en"
)

# 2. Download the file locally
url = "https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac"
local_filename = "audio_sample.flac"
r = requests.get(url)
with open(local_filename, "wb") as f:
     f.write(r.content)

# 3. Load the audio data manually
audio_data, sampling_rate = librosa.load(local_filename, sr=16000)

# 4. Transcribe with explicit chunking to avoid the 'num_frames' bug
result = transcriber(
    {"raw": audio_data, "sampling_rate": sampling_rate},
    chunk_length_s=30,
    stride_length_s=5
)
print(result["text"])

"""## More About Transformers
- All the Transformer models (GPT, BERT, T5, etc.) have been trained as language models(trained on large amounts of raw text in a self-supervised fashion).
- Through a process called transfer learning the model is fine-tuned in a supervised way.
- Large carbon foot print. Sharing the trained weights and building on top of already trained weights reduces the overall compute cost and carbon footprint of the community.


### General Transformer architecture
The model is primarily composed of two blocks:
 - **Encoder**: The encoder receives an input and builds a representation of it (its features). This means that the model is optimized to acquire understanding from the input.
 - **Decoder**: The decoder uses the encoder’s representation (features) along with other inputs to generate a target sequence. This means that the model is optimized for generating outputs.

 ### Attention layers
This layer will tell the model to pay specific attention to certain words in the sentence you passed it (and more or less ignore the others) when dealing with the representation of each word. A word by itself has a meaning, but that meaning is deeply affected by the context.
- In the encoder, the attention layers can use all the words in a sentence.
- The decoder, however, works sequentially and can only pay attention to the words in the sentence that it has already translated (so, only the words before the word currently being generated).
"""

