# -*- coding: utf-8 -*-
"""hf_difusion_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HlPjTJK3qs-7D1AX_g90mUI5XzLCM8o
"""

from diffusers import DDPMPipeline

from diffusers import DDPMPipeline, UNet2DModel, DDPMScheduler
import torch

unet = UNet2DModel.from_pretrained("google/ddpm-celebahq-256").to("cpu")
scheduler = DDPMScheduler.from_pretrained("google/ddpm-celebahq-256")
ddpm = DDPMPipeline(unet=unet, scheduler=scheduler)

image = ddpm(num_inference_steps=30).images[0]

image

from diffusers import DDPMScheduler, UNet2DModel

scheduler = DDPMScheduler.from_pretrained("google/ddpm-celebahq-256")
model = UNet2DModel.from_pretrained("google/ddpm-celebahq-256").to('cuda')

scheduler.set_timesteps(50)

import torch

sample_size = model.config.sample_size

sample_size

image.size

noise = torch.randn((1,3,sample_size,sample_size),device='cuda')

input = noise
for t in scheduler.timesteps:
  with torch.no_grad():
    noise_residual = model(input,t).sample

  previous_noisy_sample = scheduler.step(noise_residual,t,input).prev_sample
  input = previous_noisy_sample

#

input.shape

from PIL import Image
import numpy as np

image = (input /2 + 0.5).clamp(0,1).squeeze()
image = (image.permute(1,2,0)*255).round().to(torch.uint8).cpu().numpy()

image = Image.fromarray(image)

image

"""Autopipeline"""

from diffusers import AutoPipelineForText2Image

pipeline = AutoPipelineForText2Image.from_pretrained("dreamlike-art/dreamlike-photoreal-2.0", torch_dtype=torch.bfloat16, device_map="cuda")

prompt = "Cinematic photo of Elmo from Sesame street in Paris, 35 mm photo, film"
pipeline.enable_model_cpu_offload()
image= pipeline(prompt, height=256, width=256).images[0]

image