# -*- coding: utf-8 -*-
"""hf-diffuser-video_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfebFIymBx3OmfdSOEgGJLkU3d_oes7m
"""

pip install torch torchvision torchaudio diffusers transformers accelerate

import accelerate
import torch
import diffusers
import transformers

pip install opencv-python

import torch
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-video-diffusion-img2vid-xt", device_map="cuda")
pipe.to(torch.bfloat16)

pipe.enable_model_cpu_offload()

from diffusers.utils import load_image, export_to_video

prompt = "A man with short gray hair plays a red electric guitar."
image = load_image(
    "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/guitar-man.png"
)

image.size

generator = torch.manual_seed(42)

import torch
import gc

# 1. Clear memory
gc.collect()
torch.cuda.empty_cache()

# 2. Re-cast the entire pipeline to float16 to avoid BFloat16/Float32 mismatches
pipe.to(dtype=torch.float16)

# 3. Use 144p resolution
new_width, new_height = 256, 144
small_image = image.resize((new_width, new_height))

# 4. Aggressive memory optimizations
pipe.enable_sequential_cpu_offload()
pipe.enable_attention_slicing()

try:
    # Run with float16 logic
    output = pipe(
        small_image,
        width=new_width,
        height=new_height,
        num_frames=14,
        decode_chunk_size=1,
        generator=generator
    )
    frames = output.frames
    print(f"Successfully generated {len(frames)} frames.")
except Exception as e:
    print(f"Error: {e}")

# Export the generated frames to a video file
export_to_video(frames[0], "generated_video.mp4", fps=7)
print("Video saved as generated_video.mp4")