# -*- coding: utf-8 -*-
"""hf_tokenization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWCkC8Fh5NASNoQ-HX2IVD8HLrphE4lE
"""

import torch
import transformers

torch.__version__

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")

sentence =" What is the capital of France?"

input_ids = tokenizer(sentence, return_tensors="pt").input_ids

"""Token ids"""

input_ids

tokenizer.decode(286)

for token_id in input_ids[0]:
  print(tokenizer.decode(token_id))

from transformers import AutoModelForCausalLM

gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

input_ids

output = gpt2(input_ids)

"""1. batch, 2. num of tokens and 3. Unique tokens"""

output.logits.shape

final_logits = gpt2(input_ids).logits[0,-1]

final_logits

final_logits.argmax()  # token id

tokenizer.decode(final_logits.argmax())

top_10 = torch.topk(final_logits, 10)
for index in top_10.indices:
  print(tokenizer.decode(index))

final_logits.softmax(dim=0)

top10 = torch.topk(final_logits.softmax(dim=0),10)
for value, index in zip(top10.values, top10.indices):
  print(f"{tokenizer.decode(index)} -- {value.item():.1%}")

"""Text generation"""

output_ids = gpt2.generate(input_ids,max_new_tokens=20, do_sample=False, top_k=4, top_p=.95)

decoded_text = tokenizer.decode(output_ids[0])

decoded_text