# -*- coding: utf-8 -*-
"""huggingface-basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQWwM5WishwwHxnQzlAEPA5dKb8rlRRK

Install Libraries
"""

!pip install huggingface_hub transformers torch datasets

"""Import libraries"""

from transformers import pipeline
from huggingface_hub import login
from google.colab import userdata
import os
import pandas as pd

import datasets
datasets.__version__

"""Login to HuggingFace"""

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
login(token=os.environ["HF_TOKEN"])

"""Using pipelines"""

# Load the sentiment analysis pipeline
classifier = pipeline("sentiment-analysis")

# Analyze sentiment
result = classifier("I like using Hugging Face!")
print(result)

"""Datasets download"""

reviews = datasets.load_dataset("rotten_tomatoes")

"""Dataset details"""

reviews["train"]

"""Pandas"""

reviews['train'].to_pandas()

"""Use pipeline"""

pipe = pipeline("text-generation", model="gpt2", trust_remote_code=True)
messages = [
    {"role": "user", "content": "Who are you?"},
]
# For models like gpt2 which are not specifically chat models,
# the pipeline expects a plain string as input, not a list of chat dictionaries.
prompt_text = messages[0]["content"] # Extract the content of the user message
generated_text = pipe(prompt_text)
print(generated_text)

"""Finbert Model"""

pipe = pipeline("text-classification", model="ProsusAI/finbert")

pipe("This company is performing good")